# This GitHub Action builds and deploys gatsby website to
# Firebase Hosting (live channel) for every push to 'main' branch
name: Deploy to Firebase Hosting (live) on merge
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout code from our repo
      - uses: actions/checkout@v2
      # make sure that node.js version is correspond to Netlify CMS requirements
      - name: Set Node.js version
        uses: actions/setup-node@master
        with:
          node-version: "12"
      # install dependencies
      - name: Install dependencies
        run: yarn install --prod --pure-lockfile
      # build Gatsby website
      - name: Build
        run: yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GATSBY_NETLIFYCMS_FIREBASE }}"
          # IMPORTANT! Here we specify that we are deploying to LIVE channel
          channelId: live
          # IMPORTANT!!!! Update this line to your Firebase PROJECT ID
          projectId: gatsby-netlifycms-firebase
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
