# This GitHub Action creates a PR every time
# Netlify CMS updates content of our website
name: Create pull request to 'main' on push to 'publishing'
"on":
  push:
    branches:
      # watch 'publishing' branch since Netlify CMS
      # push site changes to this branch (see 'static/admin/config.yml')
      - publishing
jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      # checkout code from our repo
      - name: Checkout
        uses: actions/checkout@v2
      # create pull request to main branch
      - name: Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Updating News with ${{ github.ref }}"
          pr_body: ":crown: *An automated PR*"
